# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/courier.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/courier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/courier.proto\x12\x07\x63ourier\"c\n\nJobCreated\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\t\x12\x16\n\x0epickup_address\x18\x03 \x01(\t\x12\x18\n\x10\x64\x65livery_address\x18\x04 \x01(\t\"7\n\x0c\x44riverOnline\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x14\n\x0cvehicle_type\x18\x02 \x01(\t\"C\n\x0bJobAssigned\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x11\n\tdriver_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"1\n\x0cJobDelivered\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.courier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOBCREATED']._serialized_start=33
  _globals['_JOBCREATED']._serialized_end=132
  _globals['_DRIVERONLINE']._serialized_start=134
  _globals['_DRIVERONLINE']._serialized_end=189
  _globals['_JOBASSIGNED']._serialized_start=191
  _globals['_JOBASSIGNED']._serialized_end=258
  _globals['_JOBDELIVERED']._serialized_start=260
  _globals['_JOBDELIVERED']._serialized_end=309
# @@protoc_insertion_point(module_scope)
