# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/inventory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/inventory.proto\x12\tinventory\";\n\x0bItemCreated\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05owner\x18\x03 \x01(\t\">\n\rItemCheckedIn\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x0b\n\x03qty\x18\x02 \x01(\x05\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"?\n\x0eItemCheckedOut\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x0b\n\x03qty\x18\x02 \x01(\x05\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"a\n\x10\x43heckoutRejected\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x15\n\rrequested_qty\x18\x02 \x01(\x05\x12\x15\n\ravailable_qty\x18\x03 \x01(\x05\x12\x0e\n\x06reason\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMCREATED']._serialized_start=37
  _globals['_ITEMCREATED']._serialized_end=96
  _globals['_ITEMCHECKEDIN']._serialized_start=98
  _globals['_ITEMCHECKEDIN']._serialized_end=160
  _globals['_ITEMCHECKEDOUT']._serialized_start=162
  _globals['_ITEMCHECKEDOUT']._serialized_end=225
  _globals['_CHECKOUTREJECTED']._serialized_start=227
  _globals['_CHECKOUTREJECTED']._serialized_end=324
# @@protoc_insertion_point(module_scope)
